/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

/* Host builds intentionally keep ESP-IDF-only codecs disabled. */
#define CONFIG_GFX_EAF_JPEG_DECODE_SUPPORT 1
#define CONFIG_GFX_EAF_HEATSHRINK_SUPPORT 1
#define CONFIG_HEATSHRINK_DYNAMIC_ALLOC 1
#define CONFIG_HEATSHRINK_USE_INDEX 1

#define CONFIG_IDF_TARGET_ESP32P4 0
#define CONFIG_IDF_TARGET_ESP32S31 0
#define CONFIG_IDF_TARGET_ESP32S3 0

#define CONFIG_EMOTE_DEF_SCROLL_SPEED 20
#define CONFIG_EMOTE_DEF_LABEL_HEIGHT 32
#define CONFIG_EMOTE_DEF_LABEL_WIDTH 360
#define CONFIG_EMOTE_DEF_LABEL_Y_OFFSET 20
#define CONFIG_EMOTE_DEF_ANIMATION_FPS 24
#define CONFIG_EMOTE_DEF_FONT_COLOR 0xFFFFFF
#define CONFIG_EMOTE_DEF_BG_COLOR 0x101418
#define CONFIG_EMOTE_ASSETS_HASH_TABLE_SIZE 64
