/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_TEST_FILES           20
#define MMAP_ASSETS_TEST_CHECKSUM        0x3E83

enum MMAP_ASSETS_TEST_LISTS {
    MMAP_ASSETS_TEST_MI_1_EYE_24BIT_AAF = 0,        /*!< mi_1_eye_24bit.aaf */
    MMAP_ASSETS_TEST_MI_1_EYE_4BIT_AAF = 1,        /*!< mi_1_eye_4bit.aaf */
    MMAP_ASSETS_TEST_MI_1_EYE_8BIT_HUFF_AAF = 2,        /*!< mi_1_eye_8bit_huff.aaf */
    MMAP_ASSETS_TEST_MI_2_EYE_24BIT_AAF = 3,        /*!< mi_2_eye_24bit.aaf */
    MMAP_ASSETS_TEST_MI_2_EYE_4BIT_AAF = 4,        /*!< mi_2_eye_4bit.aaf */
    MMAP_ASSETS_TEST_MI_2_EYE_8BIT_AAF = 5,        /*!< mi_2_eye_8bit.aaf */
    MMAP_ASSETS_TEST_MI_2_EYE_8BIT_HUFF_AAF = 6,        /*!< mi_2_eye_8bit_huff.aaf */
    MMAP_ASSETS_TEST_ICON_RGB565_BIN = 7,        /*!< icon_rgb565.bin */
    MMAP_ASSETS_TEST_ICON_RGB565A8_BIN = 8,        /*!< icon_rgb565A8.bin */
    MMAP_ASSETS_TEST_MI_1_EYE_8BIT_EAF = 9,        /*!< mi_1_eye_8bit.eaf */
    MMAP_ASSETS_TEST_MI_1_EYE_8BIT_HUFF_EAF = 10,        /*!< mi_1_eye_8bit_huff.eaf */
    MMAP_ASSETS_TEST_MI_2_EYE_8BIT_HUFF_EAF = 11,        /*!< mi_2_eye_8bit_huff.eaf */
    MMAP_ASSETS_TEST_ONLY_HEATSHRINK_4BIT_EAF = 12,        /*!< only_heatshrink_4bit.eaf */
    MMAP_ASSETS_TEST_TRANSPARENT_EAF = 13,        /*!< transparent.eaf */
    MMAP_ASSETS_TEST_FLOW_FORMAT_PROBE_JPG = 14,        /*!< flow_format_probe.jpg */
    MMAP_ASSETS_TEST_FLOW_MISTY_RIDGE_JPG = 15,        /*!< flow_misty_ridge.jpg */
    MMAP_ASSETS_TEST_FLOW_NIGHT_LAKE_JPG = 16,        /*!< flow_night_lake.jpg */
    MMAP_ASSETS_TEST_FLOW_QUIET_TRAIL_JPG = 17,        /*!< flow_quiet_trail.jpg */
    MMAP_ASSETS_TEST_FLOW_WARM_HARBOR_JPG = 18,        /*!< flow_warm_harbor.jpg */
    MMAP_ASSETS_TEST_DEJAVUSANS_TTF = 19,        /*!< DejaVuSans.ttf */
};
