/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_TEST_ASSETS_FILES           8
#define MMAP_TEST_ASSETS_CHECKSUM        0x22B9

enum MMAP_TEST_ASSETS_LISTS {
    MMAP_TEST_ASSETS_ICON_RGB565_BIN = 0,        /*!< icon_rgb565.bin */
    MMAP_TEST_ASSETS_ICON_RGB565A8_BIN = 1,        /*!< icon_rgb565A8.bin */
    MMAP_TEST_ASSETS_A1_017_041_075_EAF = 2,        /*!< a1_017_041_075.eaf */
    MMAP_TEST_ASSETS_A2_018_039_063_EAF = 3,        /*!< a2_018_039_063.eaf */
    MMAP_TEST_ASSETS_A3_019_048_075_EAF = 4,        /*!< a3_019_048_075.eaf */
    MMAP_TEST_ASSETS_A4_019_083_100_EAF = 5,        /*!< a4_019_083_100.eaf */
    MMAP_TEST_ASSETS_A5_022_053_100_EAF = 6,        /*!< a5_022_053_100.eaf */
    MMAP_TEST_ASSETS_DEJAVUSANS_TTF = 7,        /*!< DejaVuSans.ttf */
};
