/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_TEST_ASSETS_FILES           15
#define MMAP_TEST_ASSETS_CHECKSUM        0x1D98

enum MMAP_TEST_ASSETS_LISTS {
    MMAP_TEST_ASSETS_MI_1_EYE_24BIT_AAF = 0,        /*!< mi_1_eye_24bit.aaf */
    MMAP_TEST_ASSETS_MI_1_EYE_4BIT_AAF = 1,        /*!< mi_1_eye_4bit.aaf */
    MMAP_TEST_ASSETS_MI_1_EYE_8BIT_AAF = 2,        /*!< mi_1_eye_8bit.aaf */
    MMAP_TEST_ASSETS_MI_1_EYE_8BIT_HUFF_AAF = 3,        /*!< mi_1_eye_8bit_huff.aaf */
    MMAP_TEST_ASSETS_MI_2_EYE_24BIT_AAF = 4,        /*!< mi_2_eye_24bit.aaf */
    MMAP_TEST_ASSETS_MI_2_EYE_4BIT_AAF = 5,        /*!< mi_2_eye_4bit.aaf */
    MMAP_TEST_ASSETS_MI_2_EYE_8BIT_AAF = 6,        /*!< mi_2_eye_8bit.aaf */
    MMAP_TEST_ASSETS_MI_2_EYE_8BIT_HUFF_AAF = 7,        /*!< mi_2_eye_8bit_huff.aaf */
    MMAP_TEST_ASSETS_ICON1_BIN = 8,        /*!< icon1.bin */
    MMAP_TEST_ASSETS_ICON5_BIN = 9,        /*!< icon5.bin */
    MMAP_TEST_ASSETS_MI_1_EYE_8BIT_HUFF_EAF = 10,        /*!< mi_1_eye_8bit_huff.eaf */
    MMAP_TEST_ASSETS_MI_2_EYE_8BIT_HUFF_EAF = 11,        /*!< mi_2_eye_8bit_huff.eaf */
    MMAP_TEST_ASSETS_TESTIMG_1_EAF = 12,        /*!< testimg_1.eaf */
    MMAP_TEST_ASSETS_TESTIMG_2_EAF = 13,        /*!< testimg_2.eaf */
    MMAP_TEST_ASSETS_DEJAVUSANS_TTF = 14,        /*!< DejaVuSans.ttf */
};
