/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_8BIT_FILES           13
#define MMAP_ASSETS_8BIT_CHECKSUM        0xAD9A

enum MMAP_ASSETS_8BIT_LISTS {
    MMAP_ASSETS_8BIT_MI_1_EYE_24BIT_AAF = 0,        /*!< mi_1_eye_24bit.aaf */
    MMAP_ASSETS_8BIT_MI_1_EYE_4BIT_AAF = 1,        /*!< mi_1_eye_4bit.aaf */
    MMAP_ASSETS_8BIT_MI_1_EYE_8BIT_HUFF_AAF = 2,        /*!< mi_1_eye_8bit_huff.aaf */
    MMAP_ASSETS_8BIT_MI_2_EYE_24BIT_AAF = 3,        /*!< mi_2_eye_24bit.aaf */
    MMAP_ASSETS_8BIT_MI_2_EYE_4BIT_AAF = 4,        /*!< mi_2_eye_4bit.aaf */
    MMAP_ASSETS_8BIT_MI_2_EYE_8BIT_AAF = 5,        /*!< mi_2_eye_8bit.aaf */
    MMAP_ASSETS_8BIT_MI_2_EYE_8BIT_HUFF_AAF = 6,        /*!< mi_2_eye_8bit_huff.aaf */
    MMAP_ASSETS_8BIT_ICON1_BIN = 7,        /*!< icon1.bin */
    MMAP_ASSETS_8BIT_ICON5_BIN = 8,        /*!< icon5.bin */
    MMAP_ASSETS_8BIT_MI_1_EYE_8BIT_EAF = 9,        /*!< mi_1_eye_8bit.eaf */
    MMAP_ASSETS_8BIT_MI_1_EYE_8BIT_HUFF_EAF = 10,        /*!< mi_1_eye_8bit_huff.eaf */
    MMAP_ASSETS_8BIT_MI_2_EYE_8BIT_HUFF_EAF = 11,        /*!< mi_2_eye_8bit_huff.eaf */
    MMAP_ASSETS_8BIT_DEJAVUSANS_TTF = 12,        /*!< DejaVuSans.ttf */
};
