#!/usr/bin/env python3
import argparse
import struct
import sys
from pathlib import Path


DEFAULT_NAME_LEN = 32
HEADER_SIZE = 12
ENTRY_META_SIZE = 12
SIGNATURE = b"\x5a\x5a"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Unpack .bin assets generated by the current packer."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        type=Path,
        help="Input .bin file path.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=Path("./unpacked"),
        type=Path,
        help="Output directory. Default: ./unpacked",
    )
    parser.add_argument(
        "-n",
        "--name-len",
        type=int,
        default=DEFAULT_NAME_LEN,
        help=f"File name byte length in mmap table. Default: {DEFAULT_NAME_LEN}",
    )
    return parser.parse_args()


def safe_name(raw_name: str, index: int) -> str:
    name = raw_name.strip().replace("\\", "_").replace("/", "_")
    if not name:
        name = f"file_{index:04d}.bin"
    return name


def main() -> int:
    args = parse_args()
    input_path: Path = args.input
    output_dir: Path = args.output
    name_len: int = args.name_len

    if name_len <= 0:
        print("error: --name-len must be a positive integer.", file=sys.stderr)
        return 2
    if not input_path.is_file():
        print(f"error: input file not found: {input_path}", file=sys.stderr)
        return 2

    blob = input_path.read_bytes()
    if len(blob) < HEADER_SIZE:
        print("error: file too small, missing header.", file=sys.stderr)
        return 2

    file_count, stored_checksum, combined_len = struct.unpack_from("<III", blob, 0)
    payload = blob[HEADER_SIZE:]

    if combined_len != len(payload):
        print(
            f"error: combined length mismatch: header={combined_len}, actual={len(payload)}",
            file=sys.stderr,
        )
        return 2

    calc_checksum = sum(payload) & 0xFFFF
    if calc_checksum != stored_checksum:
        print(
            f"error: checksum mismatch: header={stored_checksum}, actual={calc_checksum}",
            file=sys.stderr,
        )
        return 2

    entry_size = name_len + ENTRY_META_SIZE
    table_size = file_count * entry_size
    if table_size > len(payload):
        print("error: invalid mmap table size.", file=sys.stderr)
        return 2

    table = payload[:table_size]
    merged = payload[table_size:]

    output_dir.mkdir(parents=True, exist_ok=True)

    for idx in range(file_count):
        base = idx * entry_size
        name_bytes = table[base : base + name_len]
        file_size, offset, _reserved1, _reserved2 = struct.unpack_from(
            "<IIHH", table, base + name_len
        )
        name = name_bytes.split(b"\x00", 1)[0].decode("utf-8", errors="replace")
        safe_file_name = safe_name(name, idx)

        start = offset
        end = start + 2 + file_size
        if end > len(merged):
            print(
                f"error: file[{idx}] out of bounds (offset={offset}, size={file_size}).",
                file=sys.stderr,
            )
            return 2

        chunk = merged[start:end]
        if chunk[:2] != SIGNATURE:
            print(
                f"error: file[{idx}] signature mismatch at offset={offset}.",
                file=sys.stderr,
            )
            return 2

        content = chunk[2:]
        out_path = output_dir / safe_file_name
        out_path.write_bytes(content)
        print(f"[{idx + 1}/{file_count}] {out_path} ({len(content)} bytes)")

    print(f"done: unpacked {file_count} files to {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
