/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_TEST_ASSETS_FILES           99
#define MMAP_TEST_ASSETS_CHECKSUM        0x57FD

enum MMAP_TEST_ASSETS_LISTS {
    MMAP_TEST_ASSETS_01_JPG = 0,        /*!< 01.jpg */
    MMAP_TEST_ASSETS_02_JPG = 1,        /*!< 02.jpg */
    MMAP_TEST_ASSETS_03_JPG = 2,        /*!< 03.jpg */
    MMAP_TEST_ASSETS_04_JPG = 3,        /*!< 04.jpg */
    MMAP_TEST_ASSETS_05_JPG = 4,        /*!< 05.jpg */
    MMAP_TEST_ASSETS_06_JPG = 5,        /*!< 06.jpg */
    MMAP_TEST_ASSETS_07_JPG = 6,        /*!< 07.jpg */
    MMAP_TEST_ASSETS_08_JPG = 7,        /*!< 08.jpg */
    MMAP_TEST_ASSETS_09_JPG = 8,        /*!< 09.jpg */
    MMAP_TEST_ASSETS_10_JPG = 9,        /*!< 10.jpg */
    MMAP_TEST_ASSETS_11_JPG = 10,        /*!< 11.jpg */
    MMAP_TEST_ASSETS_12_JPG = 11,        /*!< 12.jpg */
    MMAP_TEST_ASSETS_13_JPG = 12,        /*!< 13.jpg */
    MMAP_TEST_ASSETS_14_JPG = 13,        /*!< 14.jpg */
    MMAP_TEST_ASSETS_15_JPG = 14,        /*!< 15.jpg */
    MMAP_TEST_ASSETS_16_JPG = 15,        /*!< 16.jpg */
    MMAP_TEST_ASSETS_17_JPG = 16,        /*!< 17.jpg */
    MMAP_TEST_ASSETS_18_JPG = 17,        /*!< 18.jpg */
    MMAP_TEST_ASSETS_19_JPG = 18,        /*!< 19.jpg */
    MMAP_TEST_ASSETS_20_JPG = 19,        /*!< 20.jpg */
    MMAP_TEST_ASSETS_21_JPG = 20,        /*!< 21.jpg */
    MMAP_TEST_ASSETS_22_JPG = 21,        /*!< 22.jpg */
    MMAP_TEST_ASSETS_23_JPG = 22,        /*!< 23.jpg */
    MMAP_TEST_ASSETS_24_JPG = 23,        /*!< 24.jpg */
    MMAP_TEST_ASSETS_25_JPG = 24,        /*!< 25.jpg */
    MMAP_TEST_ASSETS_26_JPG = 25,        /*!< 26.jpg */
    MMAP_TEST_ASSETS_27_JPG = 26,        /*!< 27.jpg */
    MMAP_TEST_ASSETS_28_JPG = 27,        /*!< 28.jpg */
    MMAP_TEST_ASSETS_29_JPG = 28,        /*!< 29.jpg */
    MMAP_TEST_ASSETS_30_JPG = 29,        /*!< 30.jpg */
    MMAP_TEST_ASSETS_31_JPG = 30,        /*!< 31.jpg */
    MMAP_TEST_ASSETS_32_JPG = 31,        /*!< 32.jpg */
    MMAP_TEST_ASSETS_33_JPG = 32,        /*!< 33.jpg */
    MMAP_TEST_ASSETS_34_JPG = 33,        /*!< 34.jpg */
    MMAP_TEST_ASSETS_35_JPG = 34,        /*!< 35.jpg */
    MMAP_TEST_ASSETS_36_JPG = 35,        /*!< 36.jpg */
    MMAP_TEST_ASSETS_37_JPG = 36,        /*!< 37.jpg */
    MMAP_TEST_ASSETS_38_JPG = 37,        /*!< 38.jpg */
    MMAP_TEST_ASSETS_39_JPG = 38,        /*!< 39.jpg */
    MMAP_TEST_ASSETS_PNG01_JPG = 39,        /*!< png01.jpg */
    MMAP_TEST_ASSETS_PNG02_JPG = 40,        /*!< png02.jpg */
    MMAP_TEST_ASSETS_PNG03_JPG = 41,        /*!< png03.jpg */
    MMAP_TEST_ASSETS_PNG04_JPG = 42,        /*!< png04.jpg */
    MMAP_TEST_ASSETS_PNG05_JPG = 43,        /*!< png05.jpg */
    MMAP_TEST_ASSETS_PNG06_JPG = 44,        /*!< png06.jpg */
    MMAP_TEST_ASSETS_PNG07_JPG = 45,        /*!< png07.jpg */
    MMAP_TEST_ASSETS_PNG08_JPG = 46,        /*!< png08.jpg */
    MMAP_TEST_ASSETS_PNG09_JPG = 47,        /*!< png09.jpg */
    MMAP_TEST_ASSETS_PNG10_JPG = 48,        /*!< png10.jpg */
    MMAP_TEST_ASSETS_PNG11_JPG = 49,        /*!< png11.jpg */
    MMAP_TEST_ASSETS_PNG12_JPG = 50,        /*!< png12.jpg */
    MMAP_TEST_ASSETS_PNG13_JPG = 51,        /*!< png13.jpg */
    MMAP_TEST_ASSETS_PNG14_JPG = 52,        /*!< png14.jpg */
    MMAP_TEST_ASSETS_PNG15_JPG = 53,        /*!< png15.jpg */
    MMAP_TEST_ASSETS_PNG16_JPG = 54,        /*!< png16.jpg */
    MMAP_TEST_ASSETS_PNG17_JPG = 55,        /*!< png17.jpg */
    MMAP_TEST_ASSETS_PNG18_JPG = 56,        /*!< png18.jpg */
    MMAP_TEST_ASSETS_PNG19_JPG = 57,        /*!< png19.jpg */
    MMAP_TEST_ASSETS_PNG20_JPG = 58,        /*!< png20.jpg */
    MMAP_TEST_ASSETS_PNG21_JPG = 59,        /*!< png21.jpg */
    MMAP_TEST_ASSETS_PNG22_JPG = 60,        /*!< png22.jpg */
    MMAP_TEST_ASSETS_PNG23_JPG = 61,        /*!< png23.jpg */
    MMAP_TEST_ASSETS_PNG24_JPG = 62,        /*!< png24.jpg */
    MMAP_TEST_ASSETS_PNG25_JPG = 63,        /*!< png25.jpg */
    MMAP_TEST_ASSETS_PNG26_JPG = 64,        /*!< png26.jpg */
    MMAP_TEST_ASSETS_PNG27_JPG = 65,        /*!< png27.jpg */
    MMAP_TEST_ASSETS_PNG28_JPG = 66,        /*!< png28.jpg */
    MMAP_TEST_ASSETS_PNG29_JPG = 67,        /*!< png29.jpg */
    MMAP_TEST_ASSETS_PNG30_JPG = 68,        /*!< png30.jpg */
    MMAP_TEST_ASSETS_PNG31_JPG = 69,        /*!< png31.jpg */
    MMAP_TEST_ASSETS_PNG32_JPG = 70,        /*!< png32.jpg */
    MMAP_TEST_ASSETS_PNG33_JPG = 71,        /*!< png33.jpg */
    MMAP_TEST_ASSETS_PNG34_JPG = 72,        /*!< png34.jpg */
    MMAP_TEST_ASSETS_PNG35_JPG = 73,        /*!< png35.jpg */
    MMAP_TEST_ASSETS_PNG36_JPG = 74,        /*!< png36.jpg */
    MMAP_TEST_ASSETS_PNG37_JPG = 75,        /*!< png37.jpg */
    MMAP_TEST_ASSETS_PNG38_JPG = 76,        /*!< png38.jpg */
    MMAP_TEST_ASSETS_PNG39_JPG = 77,        /*!< png39.jpg */
    MMAP_TEST_ASSETS_PNG40_JPG = 78,        /*!< png40.jpg */
    MMAP_TEST_ASSETS_PNG41_JPG = 79,        /*!< png41.jpg */
    MMAP_TEST_ASSETS_PNG42_JPG = 80,        /*!< png42.jpg */
    MMAP_TEST_ASSETS_PNG43_JPG = 81,        /*!< png43.jpg */
    MMAP_TEST_ASSETS_PNG44_JPG = 82,        /*!< png44.jpg */
    MMAP_TEST_ASSETS_PNG45_JPG = 83,        /*!< png45.jpg */
    MMAP_TEST_ASSETS_PNG46_JPG = 84,        /*!< png46.jpg */
    MMAP_TEST_ASSETS_PNG47_JPG = 85,        /*!< png47.jpg */
    MMAP_TEST_ASSETS_PNG48_JPG = 86,        /*!< png48.jpg */
    MMAP_TEST_ASSETS_PNG49_JPG = 87,        /*!< png49.jpg */
    MMAP_TEST_ASSETS_PNG50_JPG = 88,        /*!< png50.jpg */
    MMAP_TEST_ASSETS_PNG51_JPG = 89,        /*!< png51.jpg */
    MMAP_TEST_ASSETS_PNG52_JPG = 90,        /*!< png52.jpg */
    MMAP_TEST_ASSETS_PNG53_JPG = 91,        /*!< png53.jpg */
    MMAP_TEST_ASSETS_PNG54_JPG = 92,        /*!< png54.jpg */
    MMAP_TEST_ASSETS_PNG55_JPG = 93,        /*!< png55.jpg */
    MMAP_TEST_ASSETS_PNG56_JPG = 94,        /*!< png56.jpg */
    MMAP_TEST_ASSETS_PNG57_JPG = 95,        /*!< png57.jpg */
    MMAP_TEST_ASSETS_PNG58_JPG = 96,        /*!< png58.jpg */
    MMAP_TEST_ASSETS_PNG59_JPG = 97,        /*!< png59.jpg */
    MMAP_TEST_ASSETS_PNG60_JPG = 98,        /*!< png60.jpg */
};
