/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include "driver/gpio.h"
#include "driver/i2c_master.h"

#define HMI_RGB_BOARD_LCD_DATA_WIDTH (24)
#define HMI_RGB_BOARD_LCD_H_RES (800)
#define HMI_RGB_BOARD_LCD_V_RES (480)
#define HMI_RGB_BOARD_LCD_PIXEL_CLOCK_HZ (18 * 1000 * 1000)
#define HMI_RGB_BOARD_LCD_HSYNC_PULSE_WIDTH (1)
#define HMI_RGB_BOARD_LCD_HSYNC_BACK_PORCH (40)
#define HMI_RGB_BOARD_LCD_HSYNC_FRONT_PORCH (20)
#define HMI_RGB_BOARD_LCD_VSYNC_PULSE_WIDTH (1)
#define HMI_RGB_BOARD_LCD_VSYNC_BACK_PORCH (10)
#define HMI_RGB_BOARD_LCD_VSYNC_FRONT_PORCH (5)
#define HMI_RGB_BOARD_LCD_PCLK_ACTIVE_NEG (1)
#define HMI_RGB_BOARD_LCD_DISP_EN (GPIO_NUM_NC)
#define HMI_RGB_BOARD_LCD_BACKLIGHT (-1)
#define HMI_RGB_BOARD_LCD_BACKLIGHT_ON_LEVEL (1)
#define HMI_RGB_BOARD_LCD_BACKLIGHT_OFF_LEVEL (0)
#define HMI_RGB_BOARD_LCD_HSYNC (GPIO_NUM_44)
#define HMI_RGB_BOARD_LCD_VSYNC (GPIO_NUM_45)
#define HMI_RGB_BOARD_LCD_DE (GPIO_NUM_43)
#define HMI_RGB_BOARD_LCD_PCLK (GPIO_NUM_40)
#define HMI_RGB_BOARD_LCD_DATA0 (GPIO_NUM_8)
#define HMI_RGB_BOARD_LCD_DATA1 (GPIO_NUM_9)
#define HMI_RGB_BOARD_LCD_DATA2 (GPIO_NUM_10)
#define HMI_RGB_BOARD_LCD_DATA3 (GPIO_NUM_11)
#define HMI_RGB_BOARD_LCD_DATA4 (GPIO_NUM_12)
#define HMI_RGB_BOARD_LCD_DATA5 (GPIO_NUM_13)
#define HMI_RGB_BOARD_LCD_DATA6 (GPIO_NUM_14)
#define HMI_RGB_BOARD_LCD_DATA7 (GPIO_NUM_15)
#define HMI_RGB_BOARD_LCD_DATA8 (GPIO_NUM_16)
#define HMI_RGB_BOARD_LCD_DATA9 (GPIO_NUM_17)
#define HMI_RGB_BOARD_LCD_DATA10 (GPIO_NUM_18)
#define HMI_RGB_BOARD_LCD_DATA11 (GPIO_NUM_19)
#define HMI_RGB_BOARD_LCD_DATA12 (GPIO_NUM_33)
#define HMI_RGB_BOARD_LCD_DATA13 (GPIO_NUM_34)
#define HMI_RGB_BOARD_LCD_DATA14 (GPIO_NUM_35)
#define HMI_RGB_BOARD_LCD_DATA15 (GPIO_NUM_36)
#define HMI_RGB_BOARD_LCD_DATA16 (GPIO_NUM_37)
#define HMI_RGB_BOARD_LCD_DATA17 (GPIO_NUM_38)
#define HMI_RGB_BOARD_LCD_DATA18 (GPIO_NUM_39)
#define HMI_RGB_BOARD_LCD_DATA19 (GPIO_NUM_2)
#define HMI_RGB_BOARD_LCD_DATA20 (GPIO_NUM_3)
#define HMI_RGB_BOARD_LCD_DATA21 (GPIO_NUM_4)
#define HMI_RGB_BOARD_LCD_DATA22 (GPIO_NUM_5)
#define HMI_RGB_BOARD_LCD_DATA23 (GPIO_NUM_7)

#define HMI_RGB_LCD_H_RES HMI_RGB_BOARD_LCD_H_RES
#define HMI_RGB_LCD_V_RES HMI_RGB_BOARD_LCD_V_RES

/* -------------------------------------------------------------------------- */
/* Touch (GT1151 over I2C)                                                    */
/* -------------------------------------------------------------------------- */

#ifndef HMI_RGB_BOARD_I2C_PORT
#define HMI_RGB_BOARD_I2C_PORT (I2C_NUM_0)
#endif

#ifndef HMI_RGB_BOARD_TOUCH_I2C_SDA
#define HMI_RGB_BOARD_TOUCH_I2C_SDA (GPIO_NUM_49)
#endif

#ifndef HMI_RGB_BOARD_TOUCH_I2C_SCL
#define HMI_RGB_BOARD_TOUCH_I2C_SCL (GPIO_NUM_50)
#endif

#ifndef HMI_RGB_BOARD_TOUCH_RST
#define HMI_RGB_BOARD_TOUCH_RST (GPIO_NUM_51)
#endif

#ifndef HMI_RGB_BOARD_TOUCH_INT
#define HMI_RGB_BOARD_TOUCH_INT (GPIO_NUM_48)
#endif

#ifndef HMI_RGB_BOARD_TOUCH_I2C_HZ
#define HMI_RGB_BOARD_TOUCH_I2C_HZ (400000)
#endif
