/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_FONTS_FILES           2
#define MMAP_FONTS_CHECKSUM        0xC1AC

enum MMAP_FONTS_LISTS {
    MMAP_FONTS_FONT_PUHUI_COMMON_20_4_BIN = 0,        /*!< font_puhui_common_20_4.bin */
    MMAP_FONTS_KAITI_TTF = 1,        /*!< KaiTi.ttf */
};
