/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#if defined(__has_include)
#if __has_include("gfx_face_emote_conf.h")
#include "gfx_face_emote_conf.h"
#endif
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_DISPLAY_W
#define GFX_FACE_EMOTE_DEFAULT_DISPLAY_W 360
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_DISPLAY_H
#define GFX_FACE_EMOTE_DEFAULT_DISPLAY_H 360
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_MOUTH_X_OFS
#define GFX_FACE_EMOTE_DEFAULT_MOUTH_X_OFS 0
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_MOUTH_Y_OFS
#define GFX_FACE_EMOTE_DEFAULT_MOUTH_Y_OFS 40
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_EYE_X_HALF_GAP
#define GFX_FACE_EMOTE_DEFAULT_EYE_X_HALF_GAP 50
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_EYE_Y_OFS
#define GFX_FACE_EMOTE_DEFAULT_EYE_Y_OFS -80
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_BROW_Y_OFS_EXTRA
#define GFX_FACE_EMOTE_DEFAULT_BROW_Y_OFS_EXTRA -34
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_TIMER_PERIOD_MS
#define GFX_FACE_EMOTE_DEFAULT_TIMER_PERIOD_MS 33U
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_EYE_SEGS
#define GFX_FACE_EMOTE_DEFAULT_EYE_SEGS 24U
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_BROW_SEGS
#define GFX_FACE_EMOTE_DEFAULT_BROW_SEGS 24U
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_MOUTH_SEGS
#define GFX_FACE_EMOTE_DEFAULT_MOUTH_SEGS 32U
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_EYE_SCALE_PERCENT
#define GFX_FACE_EMOTE_DEFAULT_EYE_SCALE_PERCENT 200
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_BROW_SCALE_PERCENT
#define GFX_FACE_EMOTE_DEFAULT_BROW_SCALE_PERCENT 200
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_MOUTH_SCALE_PERCENT
#define GFX_FACE_EMOTE_DEFAULT_MOUTH_SCALE_PERCENT 200
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_BROW_THICKNESS
#define GFX_FACE_EMOTE_DEFAULT_BROW_THICKNESS 3
#endif

#ifndef GFX_FACE_EMOTE_DEFAULT_MOUTH_THICKNESS
#define GFX_FACE_EMOTE_DEFAULT_MOUTH_THICKNESS 3
#endif
